### ISSUE TITLE
price_period should be displayed not only for rent

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa#116]
## Prerequisites

- [ ] This issue is neither a bug report nor a feature request.
- [ X] I've experience in webdevelopment
- [ ] I'm new to WordPress

## Description
My client sell the property (land) with price by the unit, not the total price.  Fe. 999 / m2  I couldn't get price_period displayed because there is hardcoded display only for "rent"    This is definitely "sale".

Not should if this is a bug or not, maybe intention, but this should be somewhere in preferences. 

Thanks

**Comment by JoeHana** [comment]
Hey @Jimmi08 thanks for the feedback. As of my understanding I'm not entirly sure if price_period would be of any use for you then? The intention of the price period is indeed to display prices which are only for a specific period, which actually applies for rent objects.

In order to have something like "m²" displayed after the price, I'd suggest to have a look at this snippet which basically explains how to add "from" before the price, but with small customizations this can be also used for having some content after the price.

However, I defintely understand there might be some situations still where it might be useful to have more flexibility in this part. That's why we're already having this on our overall roadmap and will improve the whole pricing system in WPCasa by the end of this year (since this is quite a huge task).
