### ISSUE TITLE
Error getting the translation

### ISSUE THREAD

**Issue by fernandoamd** [wpsight/wpcasa#18]
the file class-wpsight-general.php
from line 31  to 130
"public static function details() "
 is not using the translation file... and always is in english

Beds:   Baths: Plot Size:   
is always in english... no matter you put in German de_DE or Spanish es_ES

**Comment by simonrimkus** [comment]
Hi Fernando,

Thanks for your feedback! But this is more a feature than a bug :)

Only the initial listing details will be translated. But then WPCasa looks for the values given on the settings page (saved as options) because users can change them there. After changing the language in your WordPress admin you can also reset the options and they will be displayed translated.

Further, users with only one language can translate there. Users with multiple languages (e.g. with Polylang and our bridge plugin) can use the string translation to translate these details.

Best regards,
Simon [WPCasa]

**Comment by fernandoamd** [comment]
Tks!!.. i reset and.. it work!..
